spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giitdb
    username: root
    password: giit123
  jpa: 
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    spring: 
       mvc:
           view:
                prefix: /WEB-INF/jsp/
                suffix: .jsp
                
